free_email_domains = {
    'gmail.com': None,
    'outlook.com': None,
    'yahoo.com': None,
    'protonmail.com': None,
    'kkoup.com': None,
    'mail.com': None,
    'zoho.com': None,
    'aol.com': None,
    'icloud.com': None,
    'tutanota.com': None,
    'onet.pl': 'Poland',
    'wp.pl': 'Poland',
    'interia.pl': 'Poland',
    'gazeta.pl': 'Poland',
    'poczta.fm': 'Poland',
    'poczta.onet.pl': 'Poland',
    'tlen.pl': 'Poland',
    'op.pl': 'Poland',
    'autograf.pl': 'Poland',
    'buziaczek.pl': 'Poland',
    'go2.pl': 'Poland',
    'hot.pl': 'Poland',
    'vp.pl': 'Poland',
    'spoko.pl': 'Poland',
    'rmf.pl': 'Poland',
    'wirtualna.pl': 'Poland',
    'poczta.wp.pl': 'Poland',
    'neostrada.pl': 'Poland',
    'poczta.tlen.pl': 'Poland',
    'gazeta.onet.pl': 'Poland',
    'opoczta.pl': 'Poland',
    'interia.eu': 'Poland',
    'chello.pl': 'Poland',
    'prokonto.pl': 'Poland',
    'spoko.net': 'Poland',
    'email.com.pl': 'Poland',
    'twojapoczta.pl': 'Poland',
    'komorkomail.pl': 'Poland',
    'onet.eu': 'Poland',
    'o2active.pl': 'Poland',
    'tlenofon.pl': 'Poland',
    'wp.eu': 'Poland',
    'o2.pl': 'Poland',
    'gmx.de': 'Germany',
    'libero.it': 'Italy',
    'rediffmail.com': 'India',
    'naver.com': 'South Korea',
    'mail.ru': 'Russia',
    'laposte.net': 'France',
    'qq.com': 'China',
    'terra.com.br': 'Brazil',
    'web.de': 'Germany',
    'daum.net': 'South Korea',
    'indiatimes.com': 'India',
    'rambler.ru': 'Russia',
    'ymail.com': 'United Arab Emirates',
    't-online.de': 'Germany',
    'ozemail.com.au': 'Australia',
    'ntlworld.com': 'United Kingdom',
    'libero.com': 'Italy',
    'sina.com.cn': 'China',
    'oi.com.br': 'Brazil',
    'voila.fr': 'France',
    'terra.com.mx': 'Mexico',
    'yahoo.co.jp': 'Japan',
    'mailinator.com': None,
    'inbox.com': None,
    'cock.li': None,
    'gmx.com': 'Germany',
    'yopmail.com': None,
    'fastmail.com': None,
    'tuta.io': None,
    'zohomail.com': None,
    'hotmail.com': None,
    'eclipso.eu': 'Germany',
    'rambler.ua': 'Ukraine',
    'arcor.de': 'Germany',
    'lycos.com': None,
    'lavabit.com': None,
    'hushmail.com': None,
    'uymail.com': None,
    'nm.ru': 'Russia',
    'inbox.lv': 'Latvia',
    'icloud.ca': 'Canada',
    'icloud.it': 'Italy',
    'msn.com': None,
    'aol.co.uk': 'United Kingdom',
    'yahoo.co.uk': 'United Kingdom',
    'yahoo.ca': 'Canada',
    'yahoo.com.au': 'Australia',
    'outlook.fr': 'France',
    'live.com.au': 'Australia',
    'gmx.at': 'Austria',
    'bluewin.ch': 'Switzerland',
    'protonmail.li': 'Liechtenstein',
    'inbox.lt': 'Lithuania',
    'yandex.ua': 'Ukraine',
    'mail.kz': 'Kazakhstan',
    'email.cz': 'Czech Republic',
    'tiscali.it': 'Italy',
    'abv.bg': 'Bulgaria',
    'orange.fr': 'France',
    'gmx.net': 'Germany',
    'yandex.kz': 'Kazakhstan',
    'yandex.by': 'Belarus',
    'ukr.net': 'Ukraine',
    'seznam.cz': 'Czech Republic',
    'swissmail.com': 'Switzerland',
    'webmail.co.za': 'South Africa',
    'mail.co.za': 'South Africa',
    'bigpond.com': 'Australia',
    'yandex.fr': 'France',
    'yandex.de': 'Germany',
    'zoho.com.au': 'Australia',
    'zoho.fr': 'France',
    'zoho.co.uk': 'United Kingdom',
    'zoho.ca': 'Canada',
    'zoho.co.in': 'India',
    'zoho.de': 'Germany',
    'zoho.sg': 'Singapore',
    'zoho.cn': 'China',
    'zoho.ru': 'Russia',
    'zoho.co.za': 'South Africa',
    'zoho.ie': 'Ireland',
    'zoho.jp': 'Japan',
    'zoho.it': 'Italy',
    'zoho.kr': 'South Korea',
    'zoho.com.tw': 'Taiwan',
    'zoho.mx': 'Mexico',
    'zoho.es': 'Spain',
    'zoho.co.nz': 'New Zealand',
    'zoho.com.br': 'Brazil',
    'zoho.com.tr': 'Turkey',
    'zoho.com.my': 'Malaysia',
    'zoho.com.ar': 'Argentina',
    'zoho.cl': 'Chile',
    'zoho.com.co': 'Colombia',
    'zoho.com.pe': 'Peru',
    'zoho.ae': 'United Arab Emirates',
    'zoho.com.sg': 'Singapore',
    'zoho.in': 'India',
    'zoho.com.ph': 'Philippines',
    'zoho.com.pk': 'Pakistan',
    'zoho.com.ng': 'Nigeria',
    'zoho.com.eg': 'Egypt',
    'zoho.co.ke': 'Kenya',
    'zoho.com.sa': 'Saudi Arabia',
    'zoho.com.bd': 'Bangladesh',
    'zoho.co.th': 'Thailand',
    'zoho.com.vn': 'Vietnam',
    'mail.com.tw': None,
    'zoho.us': None,
    'mail.bg': None,
    'inbox.si': None,
    'icloud.com.tw': None,
    'protonmail.eu': None,
    'mailnesia.io': None,
    'hotmail.com.au': None,
    'zohomail.eu': None,
    'gmx.co.uk': None,
    'fastmail.fm': None,
    'tutanota.de': None,
    'zoho.me': None,
    'mailnesia.com': None,
    'rocketmail.com': None,
    'runbox.com': None,
    'eclipso.at': None,
    'zoho.co': None,
    'bigmir.net': None,
    'fastmail.us': None,
    'zoho.eu': None,
    'cock.email': None,
    'mailinater.com': None,
    'outlook.jp': 'Japan',
    'rocketmail.co': None,
    'runbox.at': 'Austria',
    'yandex.lt': 'Lithuania',
    'gmx.us': 'United States',
    'inbox.eu': 'European Union',
    'tuta.press': None,
    'protonmail.me': None,
    'hotmail.co.uk': 'United Kingdom',
    'bigmir.email': 'Ukraine',
    'rambler.ee': 'Estonia',
    'arcor.at': 'Austria',
    'lycos.de': 'Germany',
    'lavabit.io': None,
    'hushmail.io': None,
    'uymail.net': None,
    'nm.at': 'Austria',
    'zoho.nl': 'Netherlands',
    'tlen.cz': 'Czech Republic',
    'go2.cz': 'Czech Republic',
    'inbox.fi': 'Finland',
    'mail.ee': 'Estonia',
    'mail.com.au': 'Australia',
    'icloud.fr': 'France',
    'icloud.de': 'Germany',
    'msn.de': 'Germany',
    'aol.de': 'Germany',
    'hotmail.de': 'Germany',
    'hotmail.fr': 'France',
    'live.de': 'Germany',
    'live.fr': 'France',
    'gmx.fr': 'France',
    'gmx.ch': 'Switzerland',
    'protonmail.com.au': 'Australia',
    'protonmail.at': 'Austria',
    'protonmail.de': 'Germany',
    'protonmail.ch': 'Switzerland',
    'protonmail.fr': 'France',
    'protonmail.it': 'Italy',
    'protonmail.nl': 'Netherlands',
    'protonmail.es': 'Spain',
    'protonmail.co.uk': 'United Kingdom',
    'protonmail.us': 'United States',
    'protonmail.ca': 'Canada',
    'protonmail.in': 'India',
    'protonmail.jp': 'Japan',
    'protonmail.sg': 'Singapore',
    'protonmail.hk': 'Hong Kong',
    'protonmail.cn': 'China',
    'protonmail.ru': 'Russia',
    'protonmail.co.za': 'South Africa',
    'protonmail.ie': 'Ireland',
    'protonmail.nz': 'New Zealand',
    'protonmail.co.nz': 'New Zealand',
    'protonmail.com.br': 'Brazil',
    'protonmail.com.mx': 'Mexico',
    'protonmail.com.tr': 'Turkey',
    'protonmail.com.my': 'Malaysia',
    'protonmail.com.ar': 'Argentina',
    'protonmail.com.cl': 'Chile',
    'protonmail.com.co': 'Colombia',
    'protonmail.com.pe': 'Peru',
    'protonmail.ae': 'United Arab Emirates',
    'protonmail.com.sa': 'Saudi Arabia',
    'freenet.de': 'Germany',
    '1und1.de': 'Germany',
    'versanet.de': 'Germany',
    'vodafone.de': 'Germany',
    'nurfuerspam.de': 'Germany',
    'emailn.de': 'Germany',
    'mailbox.org': 'Germany',
    'posteo.de': 'Germany',
    'kabelmail.de': 'Germany',
    'mail.de': 'Germany',
    'outlook.de': 'Germany',
    'yahoo.de': 'Germany',
    'me.com': None,
    'mac.com': None,
    't-online.at': 'Austria',
    'email.de': 'Germany',
    'wtnet.de': 'Germany',
    'drei.at': 'Austria',
    't-online.hu': 'Hungary',
    'yahoo.fr': 'France',
    'yahoo.it': 'Italy',
    'yahoo.es': 'Spain',
    'yahoo.com.br': 'Brazil',
    '163.com': 'China',
    '126.com': 'China',
    'sina.com': 'China',
    'sohu.com': 'China',
    'aliyun.com': 'China',
    'tom.com': 'China',
    'yeah.net': 'China',
    'foxmail.com': 'China',
    '139.com': 'China',
    '189.cn': 'China',
    '21cn.com': 'China',
    'sina.cn': 'China',
    'vip.qq.com': 'China',
    'tencent.com': 'China',
    'hotmail.com.cn': 'China',
    'yandex.com': None,
    'usa.com': 'United States',
    'live.com': None,
    'optonline.net': None,
    'sbcglobal.net': None,
    'att.net': None,
    'cox.net': None,
    'verizon.net': None,
    'earthlink.net': None,
    'netzero.net': None,
    'juno.com': None,
    'aim.com': None,
    'mail.us': 'United States',
    'email.com': None,
    'usa.net': 'United States',
    'nym.hush.com': None,
    'yandex.us': 'United States',
    'live.co.uk': 'United Kingdom',
    'btinternet.com': 'United Kingdom',
    'talktalk.net': 'United Kingdom',
    'blueyonder.co.uk': 'United Kingdom',
    'virginmedia.com': 'United Kingdom',
    'sky.com': 'United Kingdom',
    'sfr.fr': 'France',
    'bbox.fr': 'France',
    'free.fr': 'France',
    'wanadoo.fr': 'France',
    'numericable.fr': 'France',
}
