language_codes_dict = {
    "aa": ['Afar'],
    "ab": ['Abkhazian'],
    "ae": ['Avestan'],
    "af": ['Afrikaans'],
    "ak": ['Akan'],
    "am": ['Amharic'],
    "an": ['Aragonese'],
    "ar": ['Arabic'],
    "as": ['Assamese'],
    "av": ['Avaric'],
    "ay": ['Aymara'],
    "az": ['Azerbaijani'],
    "ba": ['Bashkir'],
    "be": ['Belarusian'],
    "bg": ['Bulgarian'],
    "bh": ['Bihari languages'],
    "bi": ['Bislama'],
    "bm": ['Bambara'],
    "bn": ['Bengali'],
    "bo": ['Tibetan'],
    "br": ['Breton'],
    "bs": ['Bosnian'],
    "ca": ['Catalan', 'Valencian'],
    "ce": ['Chechen'],
    "ch": ['Chamorro'],
    "co": ['Corsican'],
    "cr": ['Cree'],
    "cs": ['Czech'],
    "cu": ['Church Slavic', 'Old Slavonic', 'Church Slavonic', 'Old Bulgarian', 'Old Church Slavonic'],
    "cv": ['Chuvash'],
    "cy": ['Welsh'],
    "da": ['Danish'],
    "de": ['German'],
    "dv": ['Divehi', 'Dhivehi', 'Maldivian'],
    "dz": ['Dzongkha'],
    "ee": ['Ewe'],
    "el": ['Greek', 'Modern (1453-)'],
    "en": ['English'],
    "eo": ['Esperanto'],
    "es": ['Spanish', 'Castilian'],
    "et": ['Estonian'],
    "eu": ['Basque'],
    "fa": ['Persian'],
    "ff": ['Fulah'],
    "fi": ['Finnish'],
    "fj": ['Fijian'],
    "fo": ['Faroese'],
    "fr": ['French'],
    "fy": ['Western Frisian'],
    "ga": ['Irish'],
    "gd": ['Gaelic', 'Scottish Gaelic'],
    "gl": ['Galician'],
    "gn": ['Guarani'],
    "gu": ['Gujarati'],
    "gv": ['Manx'],
    "ha": ['Hausa'],
    "he": ['Hebrew'],
    "hi": ['Hindi'],
    "ho": ['Hiri Motu'],
    "hr": ['Croatian'],
    "ht": ['Haitian', 'Haitian Creole'],
    "hu": ['Hungarian'],
    "hy": ['Armenian'],
    "hz": ['Herero'],
    "ia": ['Interlingua (International Auxiliary Language Association)'],
    "id": ['Indonesian'],
    "ie": ['Interlingue', 'Occidental'],
    "ig": ['Igbo'],
    "ii": ['Sichuan Yi', 'Nuosu'],
    "ik": ['Inupiaq'],
    "io": ['Ido'],
    "is": ['Icelandic'],
    "it": ['Italian'],
    "iu": ['Inuktitut'],
    "ja": ['Japanese'],
    "jv": ['Javanese'],
    "ka": ['Georgian'],
    "kg": ['Kongo'],
    "ki": ['Kikuyu', 'Gikuyu'],
    "kj": ['Kuanyama', 'Kwanyama'],
    "kk": ['Kazakh'],
    "kl": ['Kalaallisut', 'Greenlandic'],
    "km": ['Central Khmer'],
    "kn": ['Kannada'],
    "ko": ['Korean'],
    "kr": ['Kanuri'],
    "ks": ['Kashmiri'],
    "ku": ['Kurdish'],
    "kv": ['Komi'],
    "kw": ['Cornish'],
    "ky": ['Kirghiz', 'Kyrgyz'],
    "la": ['Latin'],
    "lb": ['Luxembourgish', 'Letzeburgesch'],
    "lg": ['Ganda'],
    "li": ['Limburgan', 'Limburger', 'Limburgish'],
    "ln": ['Lingala'],
    "lo": ['Lao'],
    "lt": ['Lithuanian'],
    "lu": ['Luba-Katanga'],
    "lv": ['Latvian'],
    "mg": ['Malagasy'],
    "mh": ['Marshallese'],
    "mi": ['Maori'],
    "mk": ['Macedonian'],
    "ml": ['Malayalam'],
    "mn": ['Mongolian'],
    "mr": ['Marathi'],
    "ms": ['Malay'],
    "mt": ['Maltese'],
    "my": ['Burmese'],
    "na": ['Nauru'],
    "nb": ['Bokmål', 'Norwegian', 'Norwegian Bokmål'],
    "nd": ['Ndebele', 'North', 'North Ndebele'],
    "ne": ['Nepali'],
    "ng": ['Ndonga'],
    "nl": ['Dutch', 'Flemish'],
    "nn": ['Norwegian Nynorsk', 'Nynorsk', 'Norwegian'],
    "no": ['Norwegian'],
    "nr": ['Ndebele', 'South', 'South Ndebele'],
    "nv": ['Navajo', 'Navaho'],
    "ny": ['Chichewa', 'Chewa', 'Nyanja'],
    "oc": ['Occitan (post 1500)'],
    "oj": ['Ojibwa'],
    "om": ['Oromo'],
    "or": ['Oriya'],
    "os": ['Ossetian', 'Ossetic'],
    "pa": ['Panjabi', 'Punjabi'],
    "pi": ['Pali'],
    "pl": ['Polish'],
    "ps": ['Pushto', 'Pashto'],
    "pt": ['Portuguese'],
    "qu": ['Quechua'],
    "rm": ['Romansh'],
    "rn": ['Rundi'],
    "ro": ['Romanian', 'Moldavian', 'Moldovan'],
    "ru": ['Russian'],
    "rw": ['Kinyarwanda'],
    "sa": ['Sanskrit'],
    "sc": ['Sardinian'],
    "sd": ['Sindhi'],
    "se": ['Northern Sami'],
    "sg": ['Sango'],
    "si": ['Sinhala', 'Sinhalese'],
    "sk": ['Slovak'],
    "sl": ['Slovenian'],
    "sm": ['Samoan'],
    "sn": ['Shona'],
    "so": ['Somali'],
    "sq": ['Albanian'],
    "sr": ['Serbian'],
    "ss": ['Swati'],
    "st": ['Sotho', 'Southern'],
    "su": ['Sundanese'],
    "sv": ['Swedish'],
    "sw": ['Swahili'],
    "ta": ['Tamil'],
    "te": ['Telugu'],
    "tg": ['Tajik'],
    "th": ['Thai'],
    "ti": ['Tigrinya'],
    "tk": ['Turkmen'],
    "tl": ['Tagalog'],
    "tn": ['Tswana'],
    "to": ['Tonga (Tonga Islands)'],
    "tr": ['Turkish'],
    "ts": ['Tsonga'],
    "tt": ['Tatar'],
    "tw": ['Twi'],
    "ty": ['Tahitian'],
    "ug": ['Uighur', 'Uyghur'],
    "uk": ['Ukrainian'],
    "ur": ['Urdu'],
    "uz": ['Uzbek'],
    "ve": ['Venda'],
    "vi": ['Vietnamese'],
    "vo": ['Volapük'],
    "wa": ['Walloon'],
    "wo": ['Wolof'],
    "xh": ['Xhosa'],
    "yi": ['Yiddish'],
    "yo": ['Yoruba'],
    "za": ['Zhuang', 'Chuang'],
    "zh": ['Chinese'],
    "zu": ['Zulu']
}

language_countries_dict = {
    "aa": ["Ethiopia"],
    "ab": ["Abkhazia"],
    "ae": ["Afghanistan"],
    "af": ["South Africa", "Namibia", "Botswana", "Lesotho", "Zimbabwe"],
    "ak": ["Ghana"],
    "am": ["Ethiopia"],
    "an": ["Spain"],
    "ar": ["Egypt", "Algeria", "Saudi Arabia", "Iraq", "Morocco", "Sudan", "Yemen", "Syria", "Tunisia"],
    "as": ["India"],
    "av": ["Russia"],
    "ay": ["Bolivia", "Peru"],
    "az": ["Azerbaijan", "Iran"],
    "ba": ["Russia"],
    "be": ["Belarus"],
    "bg": ["Bulgaria"],
    "bh": ["India"],
    "bi": ["Vanuatu"],
    "bm": ["Mali"],
    "bn": ["Bangladesh", "India"],
    "bo": ["Tibet"],
    "br": ["France"],
    "bs": ["Bosnia and Herzegovina"],
    "ca": ["Spain", "Andorra", "Italy", "France"],
    "ce": ["Russia"],
    "ch": ["Micronesia", "Guam"],
    "co": ["France"],
    "cr": ["Canada"],
    "cs": ["Czech Republic"],
    "cu": ["Russia"],
    "cv": ["Russia"],
    "cy": ["United Kingdom"],
    "da": ["Denmark"],
    "de": ["Germany", "Austria", "Switzerland", "Belgium", "Luxembourg"],
    "dv": ["Maldives"],
    "dz": ["Bhutan"],
    "ee": ["Ghana", "Togo", "Benin"],
    "el": ["Greece", "Cyprus"],
    "en": ["United States", "United Kingdom", "Canada", "Australia", "India", "South Africa"],
    "eo": ["International"],
    "es": ["Spain", "Mexico", "Argentina", "Colombia", "Peru"],
    "et": ["Estonia"],
    "eu": ["Spain", "France"],
    "fa": ["Iran"],
    "ff": ["Senegal"],
    "fi": ["Finland"],
    "fj": ["Fiji"],
    "fo": ["Faroe Islands", "Denmark"],
    "fr": ["France", "Canada", "Belgium", "Switzerland"],
    "fy": ["Netherlands"],
    "ga": ["Ireland"],
    "gd": ["United Kingdom"],
    "gl": ["Spain"],
    "gn": ["Paraguay", "Bolivia"],
    "gu": ["India"],
    "gv": ["Isle of Man"],
    "ha": ["Nigeria"],
    "he": ["Israel"],
    "hi": ["India"],
    "ho": ["Papua New Guinea"],
    "hr": ["Croatia"],
    "ht": ["Haiti"],
    "hu": ["Hungary"],
    "hy": ["Armenia"],
    "hz": ["Namibia"],
    "ia": ["International"],
    "id": ["Indonesia"],
    "ie": ["International"],
    "ig": ["Nigeria"],
    "ii": ["China"],
    "ik": ["United States", "Canada"],
    "io": ["International"],
    "is": ["Iceland"],
    "it": ["Italy", "Switzerland"],
    "iu": ["Canada"],
    "ja": ["Japan"],
    "jv": ["Indonesia"],
    "ka": ["Georgia"],
    "kg": ["Congo"],
    "ki": ["Kenya"],
    "kj": ["Namibia"],
    "kk": ["Kazakhstan"],
    "kl": ["Greenland", "Denmark"],
    "km": ["Cambodia"],
    "kn": ["India"],
    "ko": ["South Korea", "North Korea"],
    "kr": ["Nigeria"],
    "ks": ["India", "Pakistan"],
    "ku": ["Turkey", "Iraq", "Iran", "Syria"],
    "kv": ["Russia"],
    "kw": ["United Kingdom"],
    "ky": ["Kyrgyzstan"],
    "la": ["Vatican City"],
    "lb": ["Luxembourg"],
    "lg": ["Uganda"],
    "li": ["Netherlands", "Belgium", "Germany"],
    "ln": ["Democratic Republic of the Congo"],
    "lo": ["Laos"],
    "lt": ["Lithuania"],
    "lu": ["Democratic Republic of the Congo"],
    "lv": ["Latvia"],
    "mg": ["Madagascar"],
    "mh": ["Marshall Islands"],
    "mi": ["New Zealand"],
    "mk": ["North Macedonia"],
    "ml": ["India"],
    "mn": ["Mongolia"],
    "mr": ["India"],
    "ms": ["Malaysia", "Brunei"],
    "mt": ["Malta"],
    "my": ["Myanmar"],
    "na": ["Nauru"],
    "nb": ["Norway"],
    "nd": ["Zimbabwe"],
    "ne": ["Nepal"],
    "ng": ["Angola"],
    "nl": ["Netherlands", "Belgium", "Suriname"],
    "nn": ["Norway"],
    "no": ["Norway"],
    "nr": ["South Africa"],
    "nv": ["United States"],
    "ny": ["Malawi"],
    "oc": ["France", "Spain", "Italy"],
    "oj": ["Canada", "United States"],
    "om": ["Ethiopia"],
    "or": ["India"],
    "os": ["Russia"],
    "pa": ["India", "Pakistan"],
    "pi": ["India"],
    "pl": ["Poland"],
    "ps": ["Afghanistan", "Pakistan"],
    "pt": ["Portugal", "Brazil", "Angola", "Mozambique"],
    "qu": ["Peru", "Bolivia", "Ecuador"],
    "rm": ["Switzerland"],
    "rn": ["Burundi"],
    "ro": ["Romania"],
    "ru": ["Russia", "Ukraine", "Kazakhstan", "Belarus"],
    "rw": ["Rwanda"],
    "sa": ["India"],
    "sc": ["Italy"],
    "sd": ["Pakistan"],
    "se": ["Norway", "Sweden", "Finland"],
    "sg": ["Central African Republic"],
    "si": ["Sri Lanka"],
    "sk": ["Slovakia"],
    "sl": ["Slovenia"],
    "sm": ["Samoa"],
    "sn": ["Zimbabwe"],
    "so": ["Somalia"],
    "sq": ["Albania", "Kosovo", "North Macedonia"],
    "sr": ["Serbia", "Bosnia and Herzegovina", "Montenegro", "Croatia", "Kosovo"],
    "ss": ["Eswatini", "South Africa"],
    "st": ["Lesotho", "South Africa"],
    "su": ["Indonesia"],
    "sv": ["Sweden", "Finland"],
    "sw": ["Tanzania", "Kenya", "Uganda"],
    "ta": ["India", "Sri Lanka", "Singapore", "Malaysia"],
    "te": ["India"],
    "tg": ["Tajikistan"],
    "th": ["Thailand"],
    "ti": ["Eritrea"],
    "tk": ["Turkmenistan"],
    "tl": ["Philippines"],
    "tn": ["South Africa", "Zimbabwe"],
    "to": ["Tonga"],
    "tr": ["Turkey", "Cyprus"],
    "ts": ["South Africa", "Eswatini", "Mozambique"],
    "tt": ["Russia"],
    "tw": ["Ghana"],
    "ty": ["French Polynesia"],
    "ug": ["China"],
    "uk": ["Ukraine"],
    "ur": ["Pakistan", "India"],
    "uz": ["Uzbekistan"],
    "ve": ["South Africa"],
    "vi": ["Vietnam"],
    "vo": ["International"],
    "wa": ["Belgium"],
    "wo": ["Senegal", "Gambia"],
    "xh": ["South Africa", "Zimbabwe"],
    "yi": ["International"],
    "yo": ["Nigeria", "Benin"],
    "za": ["China"],
    "zh": ["China", "Taiwan", "Singapore", "Hong Kong"],
    "zu": ["South Africa", "Zimbabwe"]
}
