from tracardi.domain.bridge import Bridge
from tracardi.service.plugin.domain.register import Form, FormGroup, FormField, FormComponent
from tracardi.service.storage.mysql.orm import BridgeService


async def bridge_init(database_name):
    bs = BridgeService(database_name)
    return await bs.insert(Bridge(
        id="778ded05-4ff3-4e08-9a86-72c0195fa95d",
        type="rest",
        name="REST API Bridge",
        description="API /track collector",
        config={
            "static_profile_id": False
        },
        form=Form(groups=[
            FormGroup(
                name="Tracker configuration",
                fields=[
                    FormField(
                        id="static_profile_id",
                        name="Allow static profile ID.",
                        description="This feature allows you to use profile IDs that were not generated by Tracardi. "
                                    "The delivered profile ID will be used to create a non-existing profile ID. However, "
                                    "please note that using this feature can pose a security risk. It's important to read "
                                    "Tracardi documentation carefully before using it.",
                        component=FormComponent(type="bool",
                                                props={"label": "Allow static, remotely defined profile ID"})
                    )
                ])
        ])
    ))
