# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\tscheduler\x1a\x1cgoogle/protobuf/struct.proto\"\xfe\x01\n\x07Payload\x12\x15\n\rcallback_host\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x12\n\nprofile_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x12\n\nevent_type\x18\x05 \x01(\t\x12+\n\nproperties\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12(\n\x07\x63ontext\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\x12(\n\x07request\x18\x08 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0c\n\x04time\x18\t \x01(\t\"x\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12%\n\x04meta\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0b\n\x03key\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0e\n\x06origin\x18\x06 \x01(\t2?\n\x07Service\x12\x34\n\x0cschedule_job\x12\x12.scheduler.Payload\x1a\x0e.scheduler.Job\"\x00\x62\x06proto3')



_PAYLOAD = DESCRIPTOR.message_types_by_name['Payload']
_JOB = DESCRIPTOR.message_types_by_name['Job']
Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOAD,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.Payload)
  })
_sym_db.RegisterMessage(Payload)

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), {
  'DESCRIPTOR' : _JOB,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.Job)
  })
_sym_db.RegisterMessage(Job)

_SERVICE = DESCRIPTOR.services_by_name['Service']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYLOAD._serialized_start=61
  _PAYLOAD._serialized_end=315
  _JOB._serialized_start=317
  _JOB._serialized_end=437
  _SERVICE._serialized_start=439
  _SERVICE._serialized_end=502
# @@protoc_insertion_point(module_scope)
