apiVersion: v1
kind: Service
metadata:
  name: tracardi
  labels:
    app: tracardi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8686
    protocol: TCP
    name: http
  selector:
    app: tracardi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracardi-config
data:
  elastic.host: "elasticsearch:9200"
  mysql.host: "mysql:3306"
  redis.host: "redis:6379"
