name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello. Thank you for contributing to Tracardi. Someone will read you issue report shortly. If you happen to have development questions please join our slack comminity: https://join.slack.com/t/tracardi/shared_invite/zt-1bpf35skl-8Fr5FX5a6cji7tX18JNNDA"
        pr-message: "Hello. Thank you for contributing to Tracardi. Someone will review you PR shortly. If you happen to have development questions please join our slack comminity: https://join.slack.com/t/tracardi/shared_invite/zt-1bpf35skl-8Fr5FX5a6cji7tX18JNNDA"
