import random
from faker import Faker

fake = Faker()


def generate_profile_data():
    sex = random.choice(['m', 'f'])

    if sex == 'f':
        name = f"{fake.first_name_female()} {fake.last_name_female()}"
    else:
        name = f"{fake.first_name_male()} {fake.last_name_male()}"

    name = name.split()
    tn = fake.phone_number()
    return {
        "pii": {
            "firstname": name[0],
            "lastname": name[1],
            "display_name": " ".join(name),
            "birthday": fake.date_time_between(start_date='-75y', end_date='-18y').strftime("%Y-%m-%d %H:%M:%S"),
            # "language": {
            #     "native": fake.current_country_code(),
            #     "spoken": fake.current_country_code()
            # },
            "gender": "male" if sex == 'm' else "female",
            "education": {
                "level": random.choice(
                    ['Elementary school', "High school", 'University', 'Bachelor\'s Degree', 'Master\'s Degree',
                     'Doctoral Degree', 'Technical Education'])
            },
            "civil": {
                "status": random.choice(['Married', "Single"])
            },
            "attributes": {
                "height": random.randint(120, 189),
                "weight": random.randint(50, 100),
                "shoe_number": random.randint(37, 48)
            }
        },
        "contact": {
            "app": {
                "twitter": "@tracardi",
                "slack": f"@{name[1]}",
                "telegram": f"@{name[0]}",
                "whatsapp": tn,
            },
            "address": {
                "town": fake.city(),
                "country": fake.country(),
                "postcode": fake.postcode(),
                "street": fake.street_address()
            }
        },
        "media": {
            "image": f"http://tracardi.com/demo/image/female/profile_{random.randint(1, 50)}.JPG" if sex == "f" else  f"http://tracardi.com/demo/image/male/profile_{random.randint(1, 50)}.JPG",
            "webpage": "http://www.tracardi.com",
            "social": {
                "twitter": "@tracardi",
                "facebook": "tracardi",
                "youtube": random.choice(['@tracardi', '@mytag'])
            }
        },
        "job": {
            "position": random.choice(["Software Engineer",
                                       "Accountant",
                                       "Marketing Manager",
                                       "Human Resources Coordinator",
                                       "Sales Representative",
                                       "Graphic Designer",
                                       "Financial Analyst",
                                       "Project Manager",
                                       "Data Scientist",
                                       "Customer Service Representative",
                                       "Operations Manager",
                                       "Business Development Manager",
                                       "Administrative Assistant",
                                       "Product Manager",
                                       "Web Developer",
                                       "Nurse",
                                       "Teacher",
                                       "Lawyer",
                                       "Mechanical Engineer",
                                       "Social Media Manager",
                                       "Operations Analyst",
                                       "Financial Advisor",
                                       "Digital Marketing Specialist",
                                       "UX Designer",
                                       "Electrical Engineer",
                                       "Content Writer",
                                       "Pharmacist",
                                       "Executive Assistant",
                                       "HR Manager",
                                       "IT Consultant",
                                       "Research Scientist",
                                       "Sales Manager",
                                       "Supply Chain Analyst",
                                       "Civil Engineer",
                                       "Data Analyst",
                                       "Marketing Coordinator",
                                       "Account Manager",
                                       "Systems Administrator",
                                       "UX Researcher",
                                       "Legal Assistant",
                                       "Quality Assurance Specialist",
                                       "Business Analyst",
                                       "Event Planner",
                                       "Operations Coordinator",
                                       "Public Relations Specialist",
                                       "Architect",
                                       "Medical Assistant",
                                       "Financial Planner",
                                       "Digital Project Manager",
                                       "Market Research Analyst",
                                       "UX/UI Developer"]),
            "salary": random.randint(3000, 5000),
            "company": {
                "name": random.choice(["Walmart",
                                       "Target",
                                       "Starbucks",
                                       "McDonald's",
                                       "Amazon",
                                       "Acme Corporation",
                                       "XYZ Industries",
                                       "Stellar Innovations",
                                       "AlphaTech Solutions",
                                       "Quantum Dynamics",
                                       "Sunflower Enterprises",
                                       "NovaTech Systems",
                                       "Sapphire Solutions",
                                       "Horizon Ventures",
                                       "SwiftWave Technologies",
                                       "SilentStream Innovations",
                                       "AmberGlow Solutions",
                                       "Polaris Industries",
                                       "Evergreen Technologies",
                                       "Crimson Edge",
                                       "SilverLinx Solutions",
                                       "AzureWave Systems",
                                       "Meridian Enterprises",
                                       "Nimbus Innovations",
                                       "Obsidian Technologies",
                                       "Apex Innovators",
                                       "TerraNova Solutions",
                                       "PhoenixRise Ventures",
                                       "AstralPeak Technologies",
                                       "OpalSphere Systems",
                                       "ZephyrSoft Innovations",
                                       "Veridian Dynamics",
                                       "EmeraldLight Solutions",
                                       "CobaltSky Technologies",
                                       "OnyxLabs",
                                       "Cascade Industries",
                                       "Aurelius Innovations",
                                       "Quicksilver Systems",
                                       "IndigoPeak Ventures",
                                       "VantagePoint Solutions",
                                       "Crystalline Innovations",
                                       "TitanQuest Industries",
                                       "LuminousSphere Systems",
                                       "OpulentWave Technologies",
                                       "Aegis Innovators",
                                       "Eclipse Technologies",
                                       "MosaicTech Solutions",
                                       "AuroraPeak Ventures",
                                       "SilverBreeze Systems",
                                       "JadeStar Innovations",
                                       "FluxWave Technologies",
                                       "ZenithSphere Solutions",
                                       "EmberGlide Innovations",
                                       "VividPeak Systems",
                                       "MidnightCrest Ventures",
                                       "Lyft",
                                       "Airbnb",
                                       "Nike",
                                       "Adidas",
                                       "Coca-Cola",
                                       "PepsiCo",
                                       "Ford",
                                       "General Motors",
                                       "Toyota",
                                       "Honda",
                                       "Boeing",
                                       "Lockheed Martin",
                                       "Delta Air Lines",
                                       "United Airlines",
                                       "American Airlines",
                                       "AT&T",
                                       "Verizon",
                                       "T-Mobile",
                                       "Comcast",
                                       "Home Depot",
                                       "Lowe's",
                                       "UPS",
                                       "FedEx",
                                       "Walgreens",
                                       "CVS Health",
                                       "Target",
                                       "Best Buy",
                                       "Costco",
                                       "Macy's",
                                       "Gap",
                                       "H&M",
                                       "Kohl's",
                                       "JCPenney",
                                       "Dollar General",
                                       "Dollar Tree",
                                       "Rite Aid",
                                       "Whole Foods",
                                       "Trader Joe's",
                                       "Publix",
                                       "Kroger",
                                       "Acme Corporation",
                                       "XYZ Industries",
                                       "Stellar Innovations",
                                       "AlphaTech Solutions",
                                       "Quantum Dynamics",
                                       "Sunflower Enterprises",
                                       "NovaTech Systems",
                                       "Sapphire Solutions",
                                       "Horizon Ventures",
                                       "SwiftWave Technologies"
                                       ]),
                "size": random.randint(10, 300),
                "segment": random.choice([
                    "Technology",
                    "Healthcare",
                    "Finance",
                    "Retail",
                    "Manufacturing",
                    "Energy",
                    "Transportation",
                    "Hospitality",
                    "Media and Entertainment",
                    "Education",
                    "Automotive",
                    "Telecommunications",
                    "E-commerce",
                    "Aerospace",
                    "Food and Beverage",
                    "Insurance",
                    "Real Estate",
                    "Consulting",
                    "Pharmaceuticals",
                    "Fashion"
                ]),
                "country": random.choice([
                    "Afghanistan",
                    "Argentina",
                    "Australia",
                    "Brazil",
                    "Canada",
                    "China",
                    "Egypt",
                    "France",
                    "Germany",
                    "India",
                    "Indonesia",
                    "Italy",
                    "Japan",
                    "Kenya",
                    "Mexico",
                    "Netherlands",
                    "New Zealand",
                    "Nigeria",
                    "Pakistan",
                    "Peru",
                    "Philippines",
                    "Russia",
                    "Saudi Arabia",
                    "South Africa",
                    "South Korea",
                    "Spain",
                    "Sweden",
                    "Switzerland",
                    "Thailand",
                    "Turkey",
                    "Ukraine",
                    "United Arab Emirates",
                    "United Kingdom",
                    "United States",
                    "Venezuela",
                    "Vietnam",
                    "Yemen",
                    "Zambia",
                    "Zimbabwe"
                ])
            },
            "department": random.choice([
                "Human Resources",
                "Finance",
                "Marketing",
                "Sales",
                "Operations",
                "Information Technology",
                "Research and Development",
                "Customer Service",
                "Product Management",
                "Quality Assurance",
                "Supply Chain",
                "Legal",
                "Administration",
                "Business Development",
                "Public Relations",
                "Training and Development",
                "Project Management",
                "Design",
                "Procurement",
                "Strategic Planning"
            ])
        },
        "preferences": {
            "colors": random.choice(['red', "white", 'purple', 'black', 'gray', 'green', 'pink']),
            "sizes": random.choice(['xxl', "l", 's', 'm', 'xs', 'xl']),
            "devices": random.choice(['laptop', "iphone", 'samsung mobile', 'tablet', 'pc']),
            "channels": random.choice(['desktop', "mobile", 'telephone', 'direct']),
            "payments": random.choice(['card', "cash", 'transfer', 'blik']),
            "brands": random.choice(["Nike",
                                     "Adidas",
                                     "Gucci",
                                     "Levi's",
                                     "H&M",
                                     "Zara",
                                     "Under Armour",
                                     "Calvin Klein",
                                     "Tommy Hilfiger",
                                     "Ralph Lauren",
                                     "Apple",
                                     "Samsung",
                                     "Sony",
                                     "LG",
                                     "HP",
                                     "Dell",
                                     "Microsoft",
                                     "Lenovo",
                                     "Panasonic",
                                     "Philips",
                                     "Bose",
                                     "Canon",
                                     "Nikon",
                                     "GoPro",
                                     "Xiaomi",
                                     "Huawei",
                                     "OnePlus",
                                     "JBL",
                                     "Fitbit",
                                     "Garmin",
                                     "Maybelline",
                                     "L'Oréal",
                                     "MAC Cosmetics",
                                     "NARS",
                                     "Estée Lauder",
                                     "Revlon",
                                     "Covergirl",
                                     "NYX Cosmetics",
                                     "Urban Decay",
                                     "Clinique",
                                     "Anastasia Beverly Hills",
                                     "Too Faced",
                                     "Benefit Cosmetics",
                                     "Sephora",
                                     "Kylie Cosmetics",
                                     "Fenty Beauty",
                                     "ColourPop",
                                     "Tarte Cosmetics",
                                     "Huda Beauty",
                                     "Smashbox",
                                     "Procter & Gamble",
                                     "Unilever",
                                     "Coca-Cola",
                                     "PepsiCo",
                                     "Nestlé",
                                     "Kellogg's",
                                     "Johnson & Johnson",
                                     "Colgate-Palmolive",
                                     "Mars",
                                     "Kraft Heinz",
                                     "Mondelez International",
                                     "General Mills",
                                     "Danone",
                                     "Reckitt Benckiser",
                                     "The Hershey Company",
                                     "Ferrero",
                                     "Kimberly-Clark",
                                     "Conagra Brands",
                                     "L'Oréal",
                                     "The Clorox Company",
                                     "Campbell Soup Company",
                                     "P&G Gillette",
                                     "SC Johnson",
                                     "Estée Lauder",
                                     "Pernod Ricard",
                                     "Diageo",
                                     "3M",
                                     "Anheuser-Busch InBev",
                                     "Carlsberg",
                                     "Heineken",
                                     "Mondelēz International",
                                     "Nestle Purina PetCare",
                                     "Pfizer",
                                     "Unicharm",
                                     "Whirlpool",
                                     "Amazon",
                                     "Walmart",
                                     "Costco",
                                     "Target",
                                     "Lidl",
                                     "Aldi",
                                     "Kroger",
                                     "Sainsbury's",
                                     "Tesco",
                                     "Woolworths",
                                     "Müller",
                                     "Maggi",
                                     "Pampers",
                                     "Pedigree",
                                     "Kellogg's Special K",
                                     "Dove",
                                     "Sprite",
                                     "H&M",
                                     "Zara",
                                     "Forever 21",
                                     "Uniqlo",
                                     "Primark",
                                     "Gap",
                                     "Old Navy",
                                     "Topshop",
                                     "ASOS",
                                     "Mango",
                                     "Bershka",
                                     "Pull & Bear",
                                     "Urban Outfitters",
                                     "American Eagle Outfitters",
                                     "Abercrombie & Fitch",
                                     "Hollister",
                                     "Express",
                                     "Charlotte Russe",
                                     "Boohoo",
                                     "Missguided",
                                     "PrettyLittleThing",
                                     "Nasty Gal",
                                     "Fashion Nova",
                                     "Shein",
                                     "River Island",
                                     "New Look",
                                     "Hollister",
                                     "Superdry",
                                     "Forever New",
                                     "Cotton On",
                                     "C&A",
                                     "Mossimo",
                                     "Free People",
                                     "Vero Moda",
                                     "Jacqueline de Yong",
                                     "Jack & Jones",
                                     "ONLY",
                                     "Vans",
                                     "Puma",
                                     "Nike",
                                     "Adidas",
                                     "Under Armour",
                                     "Lululemon",
                                     "Reebok",
                                     "Champion",
                                     "Tommy Hilfiger",
                                     "Ralph Lauren",
                                     "Calvin Klein",
                                     "Levi's",
                                     "Wrangler",
                                     "Diesel"
                                     ]),
            "fragrances": random.choice(["Chanel No. 5",
                                         "Dior Sauvage",
                                         "Gucci Bloom",
                                         "Tom Ford Black Orchid",
                                         "Yves Saint Laurent Black Opium",
                                         "Jo Malone London English Pear & Freesia",
                                         "Marc Jacobs Daisy",
                                         "Versace Bright Crystal",
                                         "Calvin Klein Eternity",
                                         "Paco Rabanne 1 Million",
                                         "Dolce & Gabbana Light Blue",
                                         "Burberry Brit",
                                         "Chloe Eau de Parfum",
                                         "Giorgio Armani Acqua di Gio",
                                         "Viktor & Rolf Flowerbomb",
                                         "Givenchy Ange ou Demon",
                                         "Jean Paul Gaultier Le Male",
                                         "Thierry Mugler Alien",
                                         "Hermes Terre d'Hermes",
                                         "Yves Saint Laurent La Nuit de L'Homme",
                                         "Dior J'adore",
                                         "Carolina Herrera Good Girl",
                                         "Dolce & Gabbana The One",
                                         "Paco Rabanne Lady Million",
                                         "Guerlain Shalimar",
                                         "Tom Ford Tobacco Vanille",
                                         "Chanel Coco Mademoiselle",
                                         "Yves Saint Laurent Mon Paris",
                                         "Gucci Guilty",
                                         "Versace Eros",
                                         "Marc Jacobs Decadence",
                                         "Viktor & Rolf Spicebomb",
                                         "Calvin Klein CK One",
                                         "Bvlgari Omnia Crystalline",
                                         "Jimmy Choo Eau de Parfum",
                                         "Hugo Boss Boss Bottled",
                                         "Prada Candy",
                                         "Guerlain La Petite Robe Noire",
                                         "Chanel Chance",
                                         "Dior Homme",
                                         "Givenchy Very Irrésistible",
                                         "Yves Saint Laurent Opium",
                                         "Issey Miyake L'Eau d'Issey",
                                         "Tom Ford Neroli Portofino",
                                         "Gucci Guilty Absolute",
                                         "Jo Malone London Lime Basil & Mandarin",
                                         "Montblanc Legend",
                                         "Ralph Lauren Polo Blue",
                                         "Lancome La Vie Est Belle",
                                         "Paco Rabanne Invictus",
                                         "Burberry London",
                                         "Chloe Nomade"]),
            "services": random.choice(["Healthcare",
                                       "Financial Services",
                                       "Legal Services",
                                       "Information Technology",
                                       "Marketing and Advertising",
                                       "Consulting",
                                       "Transportation and Logistics",
                                       "Hospitality",
                                       "Education and Training",
                                       "Real Estate",
                                       "Insurance",
                                       "Fitness and Wellness",
                                       "Event Planning",
                                       "Home Repair and Maintenance",
                                       "Beauty and Spa",
                                       "Travel and Tourism",
                                       "Graphic Design",
                                       "Photography",
                                       "Web Development",
                                       "Social Media Management"
                                       ])
        },
        "loyalty": {
            "codes": random.choice(['holiday2023', "but1get2", 'quickcash', 'free2']),
            "card": {
                "issuer": random.choice([
                    "Jack & Jones",
                    "ONLY",
                    "Vans",
                    "Puma",
                    "Nike",
                    "Adidas",
                    "Under Armour",
                    "Lululemon",
                    "Reebok",
                    "Champion",
                    "Tommy Hilfiger",
                    "Ralph Lauren",
                    "Calvin Klein"]),
                "expires": fake.date_time_between(start_date='-1m', end_date='+1y').strftime("%Y-%m-%d %H:%M:%S"),
                "points": random.randint(0, 100)
            }
        }
    }
